[build]
    publish = "dist"
    functions = "functions"

[[redirects]]
    from = "/backoffice/users"
    to = "https://backoffice.lingzhiglobal.com/api/v2/public/users/"
    status = 200
    force = true
    [redirects.headers]
        x-company-code = "XBU"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = "Content-Type"
        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"